### ISSUE TITLE
[REQ] Monika - Freedom

### ISSUE THREAD

**Issue by KAutumnrain** [gsuberland/dnb#1]
**Have you searched the playlist to see if it's already in there?**

YES 
[More specifically, I checked the JSON file since the desktop app appears to lack the 'search in playlist' functionality present on mobile]

**Have you searched the issues to see if someone already suggested it?**

YES

**What is the Spotify link for the track?**

https://open.spotify.com/track/7qq2A0xLC3DdeFbSmrM97W?si=d61b075853f94aba

**What is the track title?**

Monika - Freedom

Seems like you have a wide range of the liquid sphere already so hopefully this suggestion isn't too far out of the ballpark :)

**Comment by gsuberland** [comment]
Nice chill track, thanks. Added.

**Comment by gsuberland** [comment]
Nice chill track, thanks. Added.

**Comment by gsuberland** [comment]
FWIW, the desktop app _should_ have a little search icon on the right when you're in a playlist, next to where it says which field is being sorted.

![image](https://github.com/gsuberland/dnb/assets/6430604/1ed82a4d-3cf9-44f6-a23c-ef043f631c9d)

**Comment by KAutumnrain** [comment]
Oh I see. Thanks. I can't believe it passed me by 😅
